name = "esp32s3_blinky"
description = "Espressif esp32s3_blinky"
version = "0.1.0-dev"

authors = ["Joe Beazelman"]
maintainers = ["Joe Beazelman <joebeazelman@gmail.com>"]
maintainers-logins = ["joebeazelman"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["esp32s3", "xtensa", "blinky"]

executables = ["esp32s3_blinky"]

[[depends-on]]
esp32s3_hal = "0.1.0-dev"  

[[pins]]
esp32s3_hal = { path = "../esp32s3_hal" }